apiVersion: deploy.k8s.jacob.work/v1alpha1
kind: DeploymentTest
metadata:
  name: nginx
spec:
  job:
    backoffLimit: 6
    activeDeadlineSeconds: 60
    template:
      spec:
        restartPolicy: Never
        containers:
          - name: curl
            image: appropriate/curl:latest
            # curl nginx service with a timeout of 2 seconds
            command: ["curl", "http://nginx"]
            args: ["--max-time", "2", "--silent", "--verbose"]
